services:
  metabase:
    image: metabase/metabase:latest
    container_name: aqi-metabase
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      MB_SITE_NAME: "AQI Global Dashboard"
      MB_SITE_URL: http://localhost:3001
    volumes:
      - ./metabase-data:/metabase.db
    restart: unless-stopped
